server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml   #mybatis的配置文件位置
  type-aliases-package: com.sff.spring.cloud.api          #所有entity类所在的包
  mapper-locations: classpath:mybatis/mapper/*.xml                  #mapper的映射文件

spring:
  application:
    name: spring-cloud-provider-dept      #对外暴露的微服务名称，很重要
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sff_test
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource      # 指定自己使用的数据源

    # DruidDataSource 其他属性配置
    druid:
     initialSize: 5
     minIdle: 5
     maxActive: 20
     maxWait: 60000
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: SELECT 1 FROM DUAL
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 20
     useGlobalDataSourceStat: true
     filter:
      stat:
       enabled: true
       log-slow-sql: true
      wall:
       enabled: true

