server:
  port: 8080

spring:
  application:
    name: spring-cloud-consumer-dept

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server01.com:7001/eureka/,http://eureka-server04.com:7004/eureka/
  instance:
    instance-id: consumer-client-dept
    prefer-ip-address: true
