server:
  port: 7001

# eureka 单机版配置
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false # false 表示不像注册中心注册自己
#    fetchRegistry: false # false 表示自己就是注册中心，责任是维护实例，而不用去检束实例
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


# eureka 集群版配置
eureka:
  instance:
    hostname: eureka-server01.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server02.com:7002/eureka/,http://eureka-server03.com:7003/eureka/